### ISSUE TITLE
Performances of boost.simd emulation mode

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#11]
- [x] Make bigger pack implemented as 2 smaller one (multipump)
- [ ] Make smaller vector of supported type use vector type + masking if needed

**Comment by jfalcou** [comment]
as @timblechmann noted in a private email, using partially masked SIMD register is maybe better than using arrays. This has to be investigated/benchmarked.

**Comment by jfalcou** [comment]
See : https://github.com/NumScale/boost.simd/issues
Will be fixed in new Boost.SIMD

**Comment by jfalcou** [comment]
We implement emualtion as either array of scalar for small N and array of pack for bigger N. The recetly merged automap make it so we take advantage of this structure. Last step to close this is to actually make some benchmarks on emulated values.

**Comment by jfalcou** [comment]
Other point was that the old catch-all implementation were also catching cases where a scalar emulation would have been better. The fix is to constraint the general caes to be selected only if the type is actually native. It also solves a bunch of aliasing issues.

**Comment by jfalcou** [comment]
After a very short test : 
- pack with cardinal larger than native one seems to generate good code. Some function are not because of a slight oversight that need to be fixed
- pack of smaller size is craptastic. We need to test the "underuse existing register" techniques whenever possible, keepign the "emulates as an array" for type which are not supported at all (think double on altivec).

**Comment by jfalcou** [comment]
[ ] Make bigger pack implemented as 2 smaller one (multipump)
[ ] Make smaller vector of supported type use vector type + masking if needed
