### ISSUE TITLE
Passing and returning of SIMD vectors

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#12]
MSVC and possibly some other compilers may do a stack dance instead of using registers when handling packs.

**Comment by mgaunard** [comment]
I've recently experimented with `__vectorcall` using some version of MSVC12; it seems to be buggy as hell, with completely bad codegen for a function as simple as

```
native<float, tag::see_> foo(native<float, tag::sse_> a, native<float, tag::sse_> b)
{
    return b;
}
```

Codegen was just `ret` on x86 32-bits, same as `return a;`.

You might want to test compiler versions before implementing this generally.

**Comment by psiha** [comment]
How was this resolved/fixed? Do you now use compiler native vector support?

ps. __vectorcall 'worked for me' (and msvc12 had 5 updates so far so maybe you need to update it)...

**Comment by jfalcou** [comment]
wrong button. I wanted to close something else :E

**Comment by psiha** [comment]
Finally https://blogs.msdn.microsoft.com/vcblog/2016/05/04/new-code-optimizer
(we can only hope it too will start transforming your by-ref into by-regvalue calls ;D)

**Comment by mgaunard** [comment]
There is possibly a version of MSVC12 where it works properly, I'm just saying this needs to be properly tested as at least my version my bugged (I think that was 32-bit only)

**Comment by jfalcou** [comment]
Boost.SIMD now requries MSVC15 in which codegen looks very correct by just addign /Gv globally.

**Comment by psiha** [comment]
I would reopen this if I could :P
- there is no msvc15, only visual studio 2015 which has msvc14 and visual studio 2017 which has msvc14.1 (which is still in release candidate phase)
- the original issue was about much more than just the coding convention
- in fact the coding convention cannot in any way solve the problem of passing vectors by ref (explained in detail in the original ticket)
- msvc codegen may look 'ok' (compared to the previous versions) only when it inlines a particular function but when it does not or when the function crosses TU boundaries it does not (in the latter case no compiler can fix your inefficient API/ABI)...

**Comment by jfalcou** [comment]
So : 

- there is no msvc15, only visual studio 2015 which has msvc14 and visual studio 2017 which has msvc14.1 (which is still in release candidate phase). 

  Indeed bad phrasing on my side.

For the rest, digging into the old issues : 
 - we do enforce passing scalar by value
 - a bunch of file use native type by value as input. It probably not generalize but it can be done.
 - "smaller" emualted vector are gonna be implemented as partial regular vector, restricting the number of uses of array of scalar
 - returning multiple vector is already done and no function using reference-as-output exist anymore
 
My main issue with your old issues, it that it was a large swat of remarks with no simple/single repro I can use to fix them. So if any of the old issues are still up (not sure they're all), feel free to submit a decently sized issue with something I can reproduce on my MSVC, check chanegs and see if the codegen is better. 

See #347 as ana example of a proper report of MSVC issue : I know what the problem was, I checked them and reproduced them then now, I know I need to fix them and how. So if indeed somethign still bad, it may be, feed us focused issues with a repro.
