### ISSUE TITLE
The state of boost.simd

### ISSUE THREAD

**Issue by superbobry** [agenium-scale/boost.simd#545]
Dear boost.simd developers,

I know there is already an issue on the matter (#544) but I feel that the users deserve a bit more context on the changes the project has been going through. 

I maintain an open-source [vector library](github.com/jetbrains-research/viktor) which initially relied on hand-written intrinsics for vectorized operations but later switched to boost.simd. The result of the switch is [multiple bug reports/benchmarks](https://github.com/NumScale/boost.simd/issues?q=is%3Aissue+author%3Asuperbobry+is%3Aclosed) I did either on GitHub or on IRC. Therefore, as an active user of boost.simd, I find it odd to find out that AVX/AVX2/FMA are no longer supported only from the failing build of my library. Of course, it's OK that you want to make a product out of boost.simd, it's an advanced well engineered library. That being said, it is not OK to completely wipe-out features without any prior notice/announcement to existing users.

I would greatly appreciate it, if someone from @NumScale could 

* clarify the scope of the boost.simd and define the boundary the between the open-source and comercial versions.  
* explain what would happen with older verions of the library available either as local checkouts or via forks, e.g. [this](https://github.com/remymuller/boost.simd). AFAIU these can still be used free of charge (assuming the conditions of the [Boost license](https://tldrlegal.com/license/boost-software-license-1.0-explained#summary) are satisfied. 

Sidenote: don't get me wrong, I know open-source development is hard an often unfruitful work, and I do think boost.simd got a lot of things right. I remember being constantly impressed with how enthusiastic and supportive you guys were with the issues faced by ordinary users like myself. However, I also find it a bit odd with how the boost.simd/bSIMD split turned out. I hope you could provide the answers to the questions I'm seeking.

**Comment by jfalcou** [comment]
Hi,

I am a bit swamped at the moment but I'll give you a detailed rationale later next week about the direction of this library. As for forks, I can't say anything more than the fact that Boost licensed code is indeed Boost licensed.

**Comment by ccharly** [comment]
Hi folks,

Here are some explanations on the current status of Boost.SIMD and its
future.

Boost.SIMD has since some time a proprietary counterpart called bSIMD
edited by Numscale which has all supported architectures (Intel up to
AVX512, PPC up to VSX and ARM up to Aarch64).

ARM released its new SVE architecture specifications several months ago
which emphasize on vector length agnostic programming. In order for
Boost.SIMD and bSIMD to support this architecture and keeps both SVE
promises and its own promises it has to undergo massive changes 
including
its core.

Doing these changes takes some time and we also take advantage of this
situation/rewriting to improve several points such as:

- lower the compiler versions that are needed to use/compile it.
- make it compatible with C89/C99/C++98.
- clean up the interface of pack.
- improve compilation time.
- add support for float16.

We will come back to you as soon as this new version is ready for release.

> -- The NUMSCALE Team

**Comment by andrelrt** [comment]
Any news about this rewritten version?
Will it support AVX and FMA again?

**Comment by gquintin** [comment]
Hi andrelrt,

Sorry for the late answer, we are almost at the end in the "testing and fixing" step for this new version. It will indeed support AVX (with or without FMA, your choice at compile time). In fact I can tell you a little more about this new version.

- It will be called NSIMD.
- It will be compatible with C89/C99/C++98/C++03/C++11/C++14/... You will be able to write generic code even in C thanks to a very thin layer of macros. The C++ API has not changed much. Porting should be easy and straightforward.
- It will have good support for float16. Intrinsics are wrapped when available (ARM, Intel converts) otherwise emulation is done with two SIMD registers of float32's.
- It will have support for AOS to/from SOA loads/stores so that processing complex numbers, RGB pictures and tensors of degree 4 will be made easier.
- We made tremendous simplifications internally so that compilation is much faster and more compilers versions are supported. We tried with MSVC 2010 with success.
- It will be possible to have custom unroll factors. The limitation on the powers of two has been removed.
- It will first support SSE2, SSE42, AVX, AVX2, AVX512 (as found on KNLs), AVX512 (as found on Skylake processors), ARM NEON and ARM SVE.
- It will also support FMA, FP16.
- Support for other architectures will come in later releases.
- We are writing an automatic system of benchmarking whose results will be exhaustive PDFs that will be downloadable from our company website.

The licensing model has also changed and will be as follow. The library will be in a form of a binary that will be available for

- Linux Intel and ARM,
- Windows Intel.

It will be a freeware, that will be available from our company website. You will be able to use, develop with it and include it in your products. "Little" functions such as add, sub, mul, ... for performance reasons will be in header files. You will be able to purchase support for the library if you need it.

-- Numscale
