### ISSUE TITLE
Utilize GCC and Clang native SIMD support

### ISSUE THREAD

**Issue by ccharly** [agenium-scale/boost.simd#8]
Pretty self explanatory.

[original issue here](https://github.com/jfalcou/nt2/issues/341).

**Comment by jfalcou** [comment]
related to #12 , closing and merging into the other issue

**Comment by psiha** [comment]
Same thing as the other issue it was merged into: you fixed/implemented nothing...remember Joel that at one point you tested a pack implementation based on native compiler vectors and got better codegen...

**Comment by jfalcou** [comment]
Multiple stuff changed since : the fact we don't have the proto layer anymore, that we enforced the pass-by-value liek we did before etc... My experience with the gcc native type was good except, I can't have member types nor functions on them like ::static_size and other thing. Moreover, it was mostly for supporting larger vector, thing we do manually now with correct results.
